# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_ <- function(x) {
    .Call(`_ourParallel_distance_`, x)
}

distance_parallel_ <- function(x) {
    .Call(`_ourParallel_distance_parallel_`, x)
}

dosomething_ <- function(x, time) {
    .Call(`_ourParallel_dosomething_`, x, time)
}

